
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 20;
  public static final int C_PAREN = 29;
  public static final int O_PAREN = 28;
  public static final int INT = 9;
  public static final int O_CBRACKET = 32;
  public static final int MINUS = 19;
  public static final int STATIC = 5;
  public static final int SEMICOLON = 34;
  public static final int AND = 22;
  public static final int LT = 23;
  public static final int OR = 27;
  public static final int COMMA = 35;
  public static final int CLASS = 8;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int MAIN = 7;
  public static final int IF = 10;
  public static final int THIS = 14;
  public static final int DOT = 36;
  public static final int O_SBRACKET = 30;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int VOID = 6;
  public static final int EQ = 25;
  public static final int ELSE = 11;
  public static final int C_CBRACKET = 33;
  public static final int WHILE = 12;
  public static final int PUBLIC = 4;
  public static final int EXTENDS = 3;
  public static final int STRING = 17;
  public static final int GT = 24;
  public static final int PRINT = 2;
  public static final int LENGTH = 16;
  public static final int C_SBRACKET = 31;
  public static final int NOTEQ = 26;
  public static final int INTEGER_LITERAL = 38;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "CLASS",
  "INT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "THIS",
  "NEW",
  "LENGTH",
  "STRING",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "AND",
  "LT",
  "GT",
  "EQ",
  "NOTEQ",
  "OR",
  "O_PAREN",
  "C_PAREN",
  "O_SBRACKET",
  "C_SBRACKET",
  "O_CBRACKET",
  "C_CBRACKET",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "INTEGER_LITERAL"
  };
}

